"use client";

import { useEffect, useState } from "react";
import { AlertTriangle, ShieldCheck } from "lucide-react";
import Link from "next/link";

const CONSENT_KEY = "technicalai_consent_v1";

export default function ConsentModal() {
  const [open, setOpen] = useState(false);
  const [checked, setChecked] = useState(false);

  useEffect(() => {
    if (!localStorage.getItem(CONSENT_KEY)) {
      setOpen(true);
    }
  }, []);

  function accept() {
    localStorage.setItem(CONSENT_KEY, "1");
    setOpen(false);
  }

  if (!open) return null;

  return (
    <div className="fixed inset-0 z-[9999] flex items-center justify-center bg-black/70 backdrop-blur-sm p-4">
      <div className="bg-surface border border-border rounded-2xl shadow-2xl w-full max-w-lg flex flex-col gap-0 overflow-hidden">

        {/* Header */}
        <div className="flex items-center gap-3 px-6 pt-6 pb-4 border-b border-border">
          <div className="flex-shrink-0 w-9 h-9 rounded-full bg-amber-500/15 flex items-center justify-center">
            <AlertTriangle className="w-4.5 h-4.5 text-amber-400" />
          </div>
          <div>
            <h2 className="text-base font-semibold text-foreground">Important Disclaimer</h2>
            <p className="text-xs text-muted-foreground">Please read before continuing</p>
          </div>
        </div>

        {/* Body */}
        <div className="px-6 py-4 flex flex-col gap-4 text-sm text-muted-foreground overflow-y-auto max-h-[60vh]">

          <div className="rounded-xl bg-amber-500/8 border border-amber-500/20 px-4 py-3 text-amber-300 text-xs font-medium leading-relaxed">
            TechnicalAI is <strong className="text-amber-200">NOT a licensed financial advisor</strong> and does not provide investment advice. All content on this platform is for <strong className="text-amber-200">informational and educational purposes only</strong>.
          </div>

          <div className="flex flex-col gap-3 text-xs leading-relaxed">
            <div className="flex gap-2.5">
              <span className="mt-0.5 text-red-400 font-bold flex-shrink-0">•</span>
              <p><strong className="text-foreground">No financial advice.</strong> Nothing on this platform constitutes a recommendation to buy, sell, or hold any security, cryptocurrency, or other financial instrument.</p>
            </div>
            <div className="flex gap-2.5">
              <span className="mt-0.5 text-red-400 font-bold flex-shrink-0">•</span>
              <p><strong className="text-foreground">AI-generated analysis.</strong> Pattern detection, trade setups, and price targets are generated by artificial intelligence. AI can and does make errors. Do not rely solely on this tool for trading decisions.</p>
            </div>
            <div className="flex gap-2.5">
              <span className="mt-0.5 text-red-400 font-bold flex-shrink-0">•</span>
              <p><strong className="text-foreground">Risk of loss.</strong> Trading and investing in financial markets involves substantial risk of loss, including the potential loss of all invested capital. Past performance is not indicative of future results.</p>
            </div>
            <div className="flex gap-2.5">
              <span className="mt-0.5 text-red-400 font-bold flex-shrink-0">•</span>
              <p><strong className="text-foreground">Consult a professional.</strong> Always consult a qualified and licensed financial advisor before making any investment decisions.</p>
            </div>
            <div className="flex gap-2.5">
              <span className="mt-0.5 text-red-400 font-bold flex-shrink-0">•</span>
              <p><strong className="text-foreground">No guarantees.</strong> We make no representation or warranty that any analysis, signal, or forecast is accurate, complete, or suitable for any particular purpose.</p>
            </div>
          </div>

          <p className="text-xs text-muted-foreground/70 leading-relaxed">
            By continuing, you confirm that you have read, understood, and agree to our{" "}
            <Link href="/legal/terms" target="_blank" className="text-accent hover:underline">Terms of Service</Link>
            {" "}and{" "}
            <Link href="/legal/privacy" target="_blank" className="text-accent hover:underline">Privacy Policy</Link>.
          </p>
        </div>

        {/* Footer */}
        <div className="px-6 py-4 border-t border-border flex flex-col gap-3">
          <label className="flex items-start gap-3 cursor-pointer select-none">
            <input
              type="checkbox"
              checked={checked}
              onChange={(e) => setChecked(e.target.checked)}
              className="mt-0.5 w-4 h-4 rounded border-border accent-accent flex-shrink-0 cursor-pointer"
            />
            <span className="text-xs text-muted-foreground leading-relaxed">
              I understand that this platform does not provide financial advice and that all analysis is AI-generated and informational only. I acknowledge the risks involved in trading and agree to the Terms of Service and Privacy Policy.
            </span>
          </label>

          <button
            onClick={accept}
            disabled={!checked}
            className="w-full flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl text-sm font-medium transition-all
              bg-accent text-white hover:bg-accent/90
              disabled:opacity-40 disabled:cursor-not-allowed disabled:hover:bg-accent"
          >
            <ShieldCheck className="w-4 h-4" />
            I Understand — Continue to TechnicalAI
          </button>
        </div>

      </div>
    </div>
  );
}
