import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — TechnicalAI",
  description: "Terms of Service for TechnicalAI. Read our disclaimer, risk disclosure, and user agreement.",
};

export default function TermsPage() {
  const effective = "March 14, 2026";
  return (
    <div className="min-h-screen bg-noise bg-grid text-foreground">
      <div className="max-w-3xl mx-auto px-6 py-16">

        <Link href="/" className="text-xs text-muted-foreground hover:text-foreground mb-8 inline-block">
          ← Back to TechnicalAI
        </Link>

        <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-10">Effective date: {effective}</p>

        <div className="prose prose-invert prose-sm max-w-none flex flex-col gap-8 text-muted-foreground leading-relaxed">

          {/* 1 */}
          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">1. Acceptance of Terms</h2>
            <p>
              By accessing or using TechnicalAI ("the Platform", "we", "our", "us"), you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you must not use the Platform.
            </p>
          </section>

          {/* 2 */}
          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">2. Not Financial Advice — Important Disclaimer</h2>
            <div className="rounded-xl border border-amber-500/30 bg-amber-500/8 p-4 text-amber-300 text-sm leading-relaxed mb-3">
              TechnicalAI is NOT a registered investment advisor, broker-dealer, or financial planner. Nothing on this Platform constitutes financial, investment, legal, or tax advice.
            </div>
            <p>
              All content, analysis, trade setups, price targets, signals, and commentary provided by the Platform are for <strong className="text-foreground">informational and educational purposes only</strong>. They do not constitute a recommendation, solicitation, or offer to buy or sell any security, cryptocurrency, commodity, or other financial instrument.
            </p>
            <p className="mt-2">
              You should always conduct your own research and consult a licensed and qualified financial advisor, broker, or investment professional before making any investment decision.
            </p>
          </section>

          {/* 3 */}
          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">3. Risk Disclosure</h2>
            <p>
              Trading and investing in financial markets involves a <strong className="text-foreground">substantial risk of loss</strong>, up to and including the total loss of all capital invested. You should only trade or invest with money you can afford to lose.
            </p>
            <ul className="list-disc pl-5 mt-2 flex flex-col gap-1">
              <li>Past performance is not indicative of future results.</li>
              <li>Hypothetical or simulated performance results have limitations and may not reflect actual trading outcomes.</li>
              <li>Price targets, stop levels, and pattern signals are algorithmic estimates and are not guarantees of performance.</li>
              <li>Markets can be highly volatile and unpredictable. Prices may move against your position rapidly and without warning.</li>
            </ul>
          </section>

          {/* 4 */}
          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">4. AI-Generated Analysis</h2>
            <p>
              Analysis, pattern detection, trade setups, and rankings on the Platform are generated by artificial intelligence (Google Gemini). AI models can make errors, produce inaccurate outputs, or fail to identify relevant information. We make no representation that AI-generated content is accurate, complete, reliable, or suitable for any particular purpose.
            </p>
            <p className="mt-2">
              The AI "Track Record" feature tracks algorithmically identified setups against their defined targets and stops. This is a historical record of the algorithm's outputs — it does not imply that future performance will be similar, and it does not constitute a verified audited trading record.
            </p>
          </section>

          {/* 5 */}
          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">5. No Warranties</h2>
            <p>
              The Platform is provided on an "as is" and "as available" basis without warranty of any kind, express or implied. We do not warrant that the Platform will be uninterrupted, error-free, or free of viruses or other harmful components. We do not warrant the accuracy, completeness, or timeliness of any data or analysis displayed.
            </p>
          </section>

          {/* 6 */}
          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">6. Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by applicable law, TechnicalAI and its operators, employees, and affiliates shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising out of or in connection with your use of the Platform, including but not limited to trading losses, loss of profits, loss of data, or any financial loss of any nature.
            </p>
            <p className="mt-2">
              Your use of the Platform and any reliance on its content is entirely at your own risk.
            </p>
          </section>

          {/* 7 */}
          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">7. User Responsibilities</h2>
            <ul className="list-disc pl-5 flex flex-col gap-1">
              <li>You are solely responsible for all trading and investment decisions you make.</li>
              <li>You must comply with all applicable laws and regulations in your jurisdiction.</li>
              <li>You must not use the Platform for any unlawful purpose.</li>
              <li>You must be of legal age to trade financial instruments in your jurisdiction.</li>
              <li>You must keep your account credentials secure and confidential.</li>
            </ul>
          </section>

          {/* 8 */}
          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">8. Third-Party Data</h2>
            <p>
              Market data displayed on the Platform is sourced from third-party providers (including Yahoo Finance). We do not guarantee the accuracy or timeliness of such data. Data may be delayed or unavailable. Do not rely on data from this Platform for time-sensitive trading decisions.
            </p>
          </section>

          {/* 9 */}
          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">9. Modifications to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. Continued use of the Platform after changes are posted constitutes acceptance of the revised Terms. It is your responsibility to review these Terms periodically.
            </p>
          </section>

          {/* 10 */}
          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">10. Contact</h2>
            <p>
              If you have any questions about these Terms, please contact us through the Platform.
            </p>
          </section>

          <div className="border-t border-border pt-6 text-xs text-muted-foreground/60">
            <Link href="/legal/privacy" className="text-accent hover:underline">Privacy Policy</Link>
            {" · "}
            <Link href="/" className="text-accent hover:underline">Back to TechnicalAI</Link>
          </div>

        </div>
      </div>
    </div>
  );
}
